services:
  react:
    build:
      context: ./
      target: dev
    command: sh -c 'pnpm install && pnpm start --host'
    environment:
      APP_TITLE: ${APP_TITLE:-TC Global Notes}
    volumes:
      - .:/code
    ports:
      - '3000:3000'
